GET http://localhost:8080/api/v1/auth/39

###
POST http://localhost:8080/api/v1/auth
Content-Type: application/json

{
  "username": "test1",
  "password": "test1",
  "role": "MASTER",
  "slackEmail": "test1@exmaple.com"
}

###
GET http://localhost:8080/api/v1/auth/company/22

###
POST http://localhost:8080/api/v1/auth/company
Content-Type: application/json

{
  "companyName": "paperCompany1",
  "companyAddress": "paperCompany1 street1",
  "companyType": "SUPPLY",
  "userId": 38,
  "hubId": 1
}

###
PATCH http://localhost:8080/api/v1/auth/company
Content-Type: application/json

{
  "companyId": 22,
  "hubId": 11
}

###
DELETE http://localhost:8080/api/v1/auth/company/22