### User find by userId
GET http://localhost:19091/api/v1/user/{{userId}}

### [Admin] User Search
GET http://localhost:19091/api/v1/admin/user

### [Admin] Create New User
POST http://localhost:19091/api/v1/admin/user
Content-Type: application/json

{
  "name": "",
  "address": "",
  "companyType": "COMPANY",
  "userId": "",
  "hubId": ""
}