### Get A Company
GET http://localhost:19092/api/v1/company/{{companyUuid}}

### Get All Companies
GET http://localhost:19092/api/v1/company

### Create Company
POST http://localhost:19092/api/v1/company
Content-Type: application/json

{
  "name": "세상에서가장맛있는족발",
  "address": "서울시 영등포구 당산동 2가 12, 1층",
  "companyType": "DEMAND",
  "userUuid": "f1c61955-e2e1-41f9-88ee-a24656e1714c",
  "hubUuid": "b0b0a5b7-58e4-4933-81bc-0ec7dc957b67"
}

### Update Company
PUT http://localhost:19092/api/v1/company
Content-Type: application/json

{
  "name": "세상에서가장맛있는족발",
  "address": "서울시 영등포구 당산동 2가 12, 1층",
  "companyType": "SUPPLY",
  "userUuid": "",
  "hubUuid": ""
}

### Delete Company
DELETE http://localhost:19092/api/v1/company/{{companyId}}


### [ADMIN] Create Company
POST http://localhost:19092/api/v1/admin/company
Content-Type: application/json

{
  "companyUuid": "",
  "hubUuid": ""
}

### [ADMIN] Update Company
PUT http://localhost:19092/api/v1/admin/company
Content-Type: application/json

{
  "companyUuid": "",
  "hubUuid": ""
}

### [ADMIN] Update Hub ID Only
PATCH http://localhost:19092/api/v1/admin/company
Content-Type: application/json

{
  "companyUuid": "",
  "hubUuid": ""
}

### [ADMIN] Delete Company
DELETE http://localhost:19092/api/v1/admin/company/{{companyId}}


### 배송 정보를 위한 내용
POST http://localhost:19092/api/v1/internal/deliverys
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyVXVpZCI6Ijg5OTY4M2U0LTAyMTItNGVjNi05YTdmLTdmNTg0NjRlOTJiZCIsInJvbGUiOiJST0xFX01BU1RFUiIsImlhdCI6MTczNDQ1NzU3MywiZXhwIjoxNzM2MjU3NTczfQ.P1TA5fEENCCWDNvPdKLErn0NpSc1WQKmlh4iBzMLpMI
Content-Type: application/json

{
  "supplierCompanyId": "ef674968-7419-4e69-94dc-a4e4aae08f94",
  "receiverCompanyId": "6f4e4608-0b9a-4fdd-9c4b-2e2efc2f7daa"
}
