### Save Prompt Template
POST http://localhost:19091/api/v1/ai/template
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyVXVpZCI6Ijg5OTY4M2U0LTAyMTItNGVjNi05YTdmLTdmNTg0NjRlOTJiZCIsInJvbGUiOiJST0xFX01BU1RFUiIsImlhdCI6MTczNDY3OTg4MSwiZXhwIjoxNzM2NDc5ODgxfQ.Dc7DvH5f6t-RQV2MU_482bby4KYv3qd5ybcbPIYIQy0
X-User-Id: 123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "template": "출발지(departure), 도착지(arrival), 경유지(‘stopover), 예상 총 이동시간(estimateTime), 희망 배송완료시간(requestDeadline)을 포함한 요청사항을 전달합니다. 오늘 한국의 날씨를 참고해서 희망 도착시간에 안전하게 배송을 완료하려면 현재 전송시간 기준 최소한 몇일몇시에 출발지에서 출발해야하는지 계산해서 알려주세요. 답변은 예상 최소 발송 시한은 00월 00일 00시 00분 입니다..와 비슷한 방식으로 만들어주세요. 그리고  30자 이내의 멘트를 넣어주세요. 멘트에는 날씨와 응원문구가 들어갑니다. 최소 출발시간 뒤에 이어서 작성해주세요. 최종 응답 내용에는 날짜와 시간을 넣어서 답변만 응답해주세요. 경유지 정보는 없을 수 도 있습니다. 전달되는 ‘estimateTime’은 ‘분’ 단위 입니다. 해당 응답은 slack 메시지로 공유하기 때문에 slack emoji 를 한 개 추가해주세요.  이하 요청사항 —>"
}


### Create Message
POST http://localhost:19094/api/v1/ai/response
Content-Type: application/json

{
  "departure": "서울특별시 송파구 송파대로 55",
  "arrival": "부산 동구 중앙대로 206",
  "stopOver": "",
  "estimateTime": "78000",
  "requestDeadline": "24년 11월 20일 12시 이전까지 꼭 배송해주세요."
}


### response
#  {
#  "success": true,
#  "response": "예상 최소 발송 시한은 11월 18일 17시 00분 입니다. 💨  오늘 서울은 쌀쌀하니 따뜻하게 챙겨 보내세요!  부산 도착 응원합니다! 👍\n"
#  }
