spring:
  application:
    name: hub-service

  profiles:
    active: dev
    include: datasource

server:
  port: 19095

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka