DROP TABLE if EXISTS p_hub_transfers;
DROP TABLE if EXISTS p_hubs;

create table p_hubs
(
    hub_id                          bigint generated by default as identity primary key,
    hub_uuid                        varchar(36)         not null unique,
    manager_id                      bigint,
    name                            varchar(200)        not null,
    address                         varchar(255)        not null,
    latitude                        double precision    not null,
    longitude                       double precision    not null,
    created_at                      timestamp(6)        not null,
    created_by                      varchar(36)         not null,
    updated_at                      timestamp(6),
    updated_by                      varchar(36),
    deleted_at                      timestamp(6),
    deleted_by                      varchar(36),
    is_deleted                      boolean             not null,
    is_public                       boolean             not null
);

create table p_hub_transfers
(
    hub_transfer_id                 bigint generated by default as identity primary key,
    hub_transfer_uuid               varchar(36)         not null unique,
    departure_hub_id                bigint              not null,
    arrival_hub_id                  bigint              not null,
    estimated_time                  integer             not null,
    estimated_distance              double precision    not null,
    created_at                      timestamp(6)        not null,
    created_by                      varchar(36)         not null,
    updated_at                      timestamp(6),
    updated_by                      varchar(36),
    deleted_at                      timestamp(6),
    deleted_by                      varchar(36),
    is_deleted                      boolean             not null,
    is_public                       boolean             not null,

    CONSTRAINT fk_departure_hub FOREIGN KEY (departure_hub_id) REFERENCES p_hubs (hub_id) ON DELETE CASCADE,
    CONSTRAINT fk_arrival_hub FOREIGN KEY (arrival_hub_id) REFERENCES p_hubs (hub_id) ON DELETE CASCADE
);
