### 상품등록-성공
POST http://localhost:8080/api/v1/admin/product
Content-Type: application/json
X-User-Id: 550e8400-e29b-41d4-a716-446655440006

{
  "companyId": "f47ac10b-58cc-4372-a567-0e02b2c3c487",
  "productHubId": "f47ac10b-58cc-4372-a567-0e02b1c3d487",
  "productName": "샤오미 발 히터",
  "productPrice": 1000,
  "productDescription": "string",
  "stockQuantity": 1000
}


### 상품등록-실패-상품가격과, 수량에 문자가 있을경우
POST http://localhost:8080/api/v1/admin/product
Content-Type: application/json
#X-User-Id: 550e8400-e29b-41d4-a716-446655440006

{
  "companyId": "f47ac10b-58cc-4372-a567-0e02b2c3c487",
  "productHubId": "f47ac10b-58cc-4372-a567-0e02b1c3d487",
  "productName": "샤오미 발 히터",
  "productPrice": "300df00",
  "productDescription": "샤오미 발히터입니다.",
  "stockQuantity": "dd"
}

### 사용자 인증 안된 경우
POST http://localhost:8080/api/v1/admin/product
Content-Type: application/json
#X-User-Id: 550e8400-e29b-41d4-a716-446655440006

{
  "companyId": "f47ac10b-58cc-4372-a567-0e02b2c3c487",
  "productHubId": "f47ac10b-58cc-4372-a567-0e02b1c3d487",
  "productName": "샤오미 발 히터",
  "productPrice": 30000,
  "productDescription": "샤오미 발히터입니다.",
  "stockQuantity": 1000
}

