spring:
  application:
    name: delivery-service
  #  sql:
  #    init:
  #      mode: always
  #      schema-locations: classpath:schema.sql
  #      data-locations: classpath:data.sql
  datasource:
    url: jdbc:postgresql://localhost:5432/mosaic
    username: root
    password: pass!
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    generate-ddl: false
    properties:
      format-sql: true
      hibernate:
        show-sql: true
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

server:
  port: 19099

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

springdoc:
  swagger-ui:
    enabled: false
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    path: /docs/delivery-service